name: berht_dev
description: "A Flutter web business card application with Cupertino design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.1
  provider: ^6.0.5
  lottie: ^2.6.0
  font_awesome_flutter: ^10.8.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/images/
    - assets/stickers/preview/
    - assets/stickers/lottie/